baseURL = "https://marketstationapartments.com"
languageCode = "en-us"
title = "Market Station Apartments | Greensboro, NC"
theme = "cryptical"
enableGitInfo = true

[Params]
  description = "Check for available units at Market Station Apartments in Greensboro, NC. View apartment types, photos, and community amenities."
  propertyAddress = "5515 W Market St, Greensboro, NC 27409"
  propertyPhone = "336-554-7913"
  propertyEmail = "marketstationmgr@gmail.com"
  authorName = "Caleb Richelson"
