baseURL = "https://liveatmarketstation.com"
languageCode = "en-us"
title = "Market Station Apartments | Greensboro, NC"
theme = "cryptical"
enableGitInfo = true

[params]
  description = "Welcome to Market Station. Spacious apartments and modern living with amenities you will love. The Greensboro lifestyle you deserve."
[params.property]
  name = "Market Station Apartments"
  phone = "336.294.0913"
  email = "marketstationmgr@gmail.com"
[params.property.address]
  line1 = "5515 West Market St"
  line2 = "Greensboro, NC 27409"
  line3 = "United States"
